// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Core.Models.MovementsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OperationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50e404fa-9668-453a-ba9c-303331a5e848"),
                            Amount = 2500.00m,
                            Category = "Salario",
                            Description = "1.Nómina Octubre",
                            OperationDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDate = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ca8ac275-3490-46b0-9326-7196ba1230bf"),
                            Amount = -800.00m,
                            Category = "Alquiler",
                            Description = "2.Alquiler piso Octubre",
                            OperationDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3c7fa20f-c048-45ee-b6b6-07a3099855c0"),
                            Amount = -120.50m,
                            Category = "Servicios públicos",
                            Description = "3.Factura Luz",
                            OperationDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("43fea005-ce95-4195-a5f2-dd0b5e9fe249"),
                            Amount = -50.25m,
                            Category = "Alimentación",
                            Description = "4.Compra Mercadona",
                            OperationDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDate = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("731deb45-9c4f-470e-b96d-2854a3e97932"),
                            Amount = -80.25m,
                            Category = "Servicios públicos",
                            Description = "5.Factura Agua",
                            OperationDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDate = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("261bf873-3891-4638-b3f4-cfc6fd7ce685"),
                            Amount = -55.00m,
                            Category = "Servicios públicos",
                            Description = "6.Factura Gas",
                            OperationDate = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDate = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9132904b-f312-4060-8f68-0a2d58c1cf23"),
                            Amount = -25.00m,
                            Category = "Alimentación",
                            Description = "7.Compra Carrefour",
                            OperationDate = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDate = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("960b50e2-c71b-4214-bad7-c4a06529f6cd"),
                            Amount = 800.00m,
                            Category = "Salario",
                            Description = "8.Nomina Noviembre",
                            OperationDate = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDate = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c6d91354-26e8-495f-8bf4-6899fa83acfa"),
                            Amount = -850.00m,
                            Category = "Alquiler",
                            Description = "9.Alquiler piso Noviembre",
                            OperationDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d203486f-ef3b-449a-8e17-e57d500e62ec"),
                            Amount = -80.00m,
                            Category = "Servicios públicos",
                            Description = "10.Factura Agua",
                            OperationDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueDate = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
